### ISSUE TITLE
Google MapのAPIを調査する

### ISSUE THREAD

**Issue by selebseed** [selebseed/transcript_minutes#1]
Google Mapの混雑状況のAPIに関する調査を行う

**Comment by stat-ki** [comment]
# 途中経過
## 調査したAPI
  - <a href="https://developers.google.com/maps/documentation/geolocation/intro?hl=ja">Geolocation</a>
    位置情報（緯度・経度）を取得するために使用する。
  - <a href="https://developers.google.com/maps/documentation/javascript/tutorial?hl=ja">Maps Javascript</a>
    地図自体の表示に使用する。
  - <a href="https://developers.google.com/places/web-service/intro?hl=ja&utm_source=google&utm_medium=cpc&utm_campaign=FY18-Q2-global-demandgen-paidsearchonnetworkhouseads-cs-maps_contactsal_saf&utm_content=text-ad-none-none-DEV_c-CRE_352248950079-ADGP_Hybrid+%7C+AW+SEM+%7C+SKWS+~+Places+%7C+BMM+%7C+Places+API-KWID_43700044579285489-kwd-475997044718-userloc_20636&utm_term=KW_%2Bplace%20%2Bapi-ST_%2Bplace+%2Bapi&gclid=Cj0KCQjw-_j1BRDkARIsAJcfmTGIKBjryxpfeL5BGIlp0YNcyXL6a5xWDaCinYL4Xp2OgxIhCx9nRowaAvOwEALw_wcB)">Place</a>
  プレイス情報の取得に使用する。
## 使用料金
従量課金制で合計$32.00/1000req程度（要検証）
## テスト内容
現在地情報を取得し、マップ上に表示。現在地周辺の店舗情報を検索し、情報を取得。
## 課題
  - PlaceAPIは混雑状況の情報を提供していないため、何らかの方法で取得する。
  - MapsAPIには地域で色分け等の表示方法がデフォルトでは存在しない。
## 所感
現在地取得から周辺施設の取得までをAPIで行い、混雑状況の取得からマッピングまでを別のツールで行うことを考えているが、実行速度や料金が大きくなりそうであるため、別の方法を検討したい。
## 今後の調査内容
  - スクレイピング方法の調査
  - 他のマップAPIの検討

**Comment by selebseed** [comment]
@stat-ki 
思ったよりAPIの料金高いね。例えば現在状況の取得をカットすれば、安くなるとかあるんかな？
合計だけじゃなくてAPIごとの料金わかると助かるかも。
あと、他のMapAPIの検討もしてみたいね。
混雑状況で座標取ってこれれば、それをマッピングすればいいだけだと思うし。
